<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Sign in</title>
        <link rel="stylesheet" href="/css/styles.css">
    </head>
    <body>

        <!-- Splash screen -->
        <section id="page-splash" class="page-splash">
            <div class="d-flex justify-content-center">
                <div class="mx-3">
                    <form id="login-form">
                        <h3>Вход</h3>
                        <input type="text" name="email" class="form-control mb-1" placeholder="email">
                        <input type="password" name="password" class="form-control mb-1" placeholder="Пароль">
                        <button type="submit" class="btn btn-outline-primary btn-block">Войти</button>

                    </form>
                </div>
            </div>
            <a href="/registration">Register new customer!</a>
            <a href="/registration">Registration</a>
        </section>
    </body>
</html>

<script src="/js/login.js"></script>
